<?php

namespace api\modules\v1\controllers\ex;

use common\helpers\ResultHelper;
use common\components\okex\Account;
use yii\rest\ActiveController;

/**
 * 账户
 *
 * Class AccountController
 * @package api\modules\v1\controllers\ex
 * @property \yii\db\ActiveRecord $modelClass
 * @author jianyan74 <751393839@qq.com>
 */
class AccountController extends ActiveController
{
    public $modelClass = '';

    protected $ex = '';

    /**
     * @var Account
     */
    protected $obj = '';

    public function init()
    {
        $this->ex = 'okex';
        if ($this->ex == 'okex') {
            $exClass = 'common\components\\'.$this->ex.'\\Account';
        }
        $this->obj = new $exClass();
    }

    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['view']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        unset($action['options']);
    }

    /**
     * 资金账户信息，多个币种
     * @return array|mixed
     */
    public function actionGetWalletInfo()
    {
        $res = $this->obj->getWalletInfo();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 单一币种账户信息
     * @return array|mixed
     */
    public function actionGetSpecialWalletInfo()
    {
        $res = $this->obj->getSpecialWalletInfo();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 资金划转
     * @return array|mixed
     */
    public function actionTransfer()
    {
        $res = $this->obj->transfer();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 提币
     * @return array|mixed
     */
    public function actionWithdrawal()
    {
        try {
            $res = $this->obj->withdrawal();
        } catch (\Exception $e) {
            return ResultHelper::json(422, '提币失败'.$e->getMessage());
        }

        return ResultHelper::json(200, '提币成功',$res);
    }

    /**
     * 账单流水
     * @return array|mixed
     */
    public function actionGetLeger()
    {
        $res = $this->obj->getLeger();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 获取充值地址
     * @return array|mixed
     */
    public function actionGetDepositAddress()
    {
        $res = $this->obj->getDepositAddress();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 获取账户资产估值
     * @return array|mixed
     */
    public function actionGetAssetValuation()
    {
        $res = $this->obj->getAssetValuation();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 获取子账户余额信息
     * @return array|mixed
     */
    public function actionGetSubAccount()
    {
        $res = $this->obj->getSubAccount();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 查询所有币种的提币记录
     * @return array|mixed
     */
    public function actionGetWithdrawalHistory()
    {
        $res = $this->obj->getWithdrawalHistory();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 查询单个币种的提币记录
     * @return array|mixed
     */
    public function actionGetCoinWithdrawalHistory()
    {
        $res = $this->obj->getCoinWithdrawalHistory();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 获取所有币种充值记录
     * @return array|mixed
     */
    public function actionGetDepositHistory()
    {
        $res = $this->obj->getDepositHistory();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 查询单个币种的充值记录
     * @return array|mixed
     */
    public function actionGetCoinDepositHistory()
    {
        $res = $this->obj->getCoinDepositHistory();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 获取币种列表
     * @return array|mixed
     */
    public function actionGetCurrencies()
    {
        $res = $this->obj->getCurrencies();
        return ResultHelper::json(200, '获取成功',$res);
    }

    /**
     * 提币手续费
     * @return array|mixed
     */
    public function actionGetWithdrawalFee()
    {
        $res = $this->obj->getWithdrawalFee();
        return ResultHelper::json(200, '获取成功',$res);
    }
}
